# Generated by Django 3.2.10 on 2022-04-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentname',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='announcedlgaresults',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='announcedpuresults',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='announcedstateresults',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='announcedwardresults',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lga',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'managed': True},
        ),
    ]
